keyword_map = {
    "rice": ("cooked_rice", "Cooked rice"),
    "nasi": ("cooked_rice", "Cooked rice"),
    "egg": ("egg", "Egg"),
    "telur": ("egg", "Egg"),
    "telor": ("egg", "Egg"),
    "chicken": ("chicken_leftover", "Chicken leftover"),
    "ayam": ("chicken_leftover", "Chicken leftover"),
    "fish": ("fish_leftover", "Fish leftover"),
    "ikan": ("fish_leftover", "Fish leftover"),
    "vegetable": ("vegetable_leftover", "Vegetable leftover"),
    "sayur": ("vegetable_leftover", "Vegetable leftover"),
    "sayuran": ("vegetable_leftover", "Vegetable leftover"),
    "cabbage": ("vegetable_leftover", "Vegetable leftover"),
    "kol": ("vegetable_leftover", "Vegetable leftover"),
    "tempe": ("tempeh_leftover", "Tempeh leftover"),
    "tempeh": ("tempeh_leftover", "Tempeh leftover"),
    "tofu": ("tofu_leftover", "Tofu leftover"),
    "tahu": ("tofu_leftover", "Tofu leftover"),
    "sambal": ("sambal", "Sambal"),
    "kecap": ("sambal", "Sambal or sweet soy sauce"),
    "saus": ("sambal", "Sauce"),
    "noodle": ("noodles_leftover", "Noodles leftover"),
    "mie": ("noodles_leftover", "Noodles leftover"),
    "bihun": ("noodles_leftover", "Noodles leftover"),
    "kwetiau": ("noodles_leftover", "Noodles leftover"),
    "bread": ("bread_leftover", "Bread leftover"),
    "roti": ("bread_leftover", "Bread leftover"),
    "beef": ("beef_leftover", "Beef leftover"),
    "daging": ("beef_leftover", "Beef leftover"),
    "rendang": ("beef_leftover", "Beef leftover"),
    "santan": ("coconut_milk_dish_leftover", "Coconut milk dish leftover"),
    "gulai": ("coconut_milk_dish_leftover", "Coconut milk dish leftover"),
    "lodeh": ("coconut_milk_dish_leftover", "Coconut milk dish leftover"),
    "opor": ("coconut_milk_dish_leftover", "Coconut milk dish leftover"),
    "pisang": ("banana_overripe", "Overripe banana"),
    "banana": ("banana_overripe", "Overripe banana"),
    "jagung": ("corn_leftover", "Corn leftover"),
    "corn": ("corn_leftover", "Corn leftover"),
    "kentang": ("potato_leftover", "Potato leftover"),
    "potato": ("potato_leftover", "Potato leftover"),
    "singkong": ("cassava_leftover", "Cassava leftover"),
    "cassava": ("cassava_leftover", "Cassava leftover"),
    "lontong": ("lontong_ketupat_leftover", "Lontong/ketupat leftover"),
    "ketupat": ("lontong_ketupat_leftover", "Lontong/ketupat leftover"),
    "bumbu": ("spice_paste_leftover", "Spice paste leftover"),
    "kelapa parut": ("grated_coconut_leftover", "Grated coconut leftover"),
}

safety_keywords = {
    "mold": "Mold mentioned. Do not recommend edible reuse.",
    "jamur": "Mold mentioned. Do not recommend edible reuse.",
    "slimy": "Slimy texture mentioned. Do not recommend edible reuse.",
    "berlendir": "Slimy texture mentioned. Do not recommend edible reuse.",
    "sour smell": "Sour smell mentioned. Do not recommend edible reuse.",
    "bau asam": "Sour smell mentioned. Do not recommend edible reuse.",
    "spoiled": "Spoilage mentioned. Do not recommend edible reuse.",
    "basi": "Spoilage mentioned. Do not recommend edible reuse.",
}


def title_from_label(label: str) -> str:
    return label.replace("_", " ").title()
